### PR TITLE
feat(numeric-locale): add numeric locale support

### PR DESCRIPTION
**Pull request by saenai255**
- Adds localized numeric system support
- Adds fallback fonts for Bengali characters

### CODE REVIEW

**Review by Henryws — CHANGES_REQUESTED** [review]
Add a Hindi font as well.

**Comment by saenai255** [comment]
> Add a Hindi font as well.

@wizard-28 could you provide 2 hindi fonts? one for regular text and one for headings

**Comment by Henryws** [comment]
https://github.com/pacstall/website/issues/397#issuecomment-1546820681

**Comment by saenai255** [comment]
> [#397 (comment)](https://github.com/pacstall/website/issues/397#issuecomment-1546820681)

one more for headings

**Comment by Henryws** [comment]
Could we not bold the font?

**Comment by saenai255** [comment]
no

**Review by Elsie19 — APPROVED** [review]

**Pull request merged**
